config/routes.rb
Rails.application.routes.draw do
  resources :games do 
    member do 
      get 'play'
      get 'debug'
      get 'query'
      get 'query2'
      get 'copy'
    end
  end
  
  devise_for :users
  get 'welcome/index'
  get 'welcome/rules' => "welcome#rules"
  get 'welcome/help' => "welcome#help"
  get 'welcome/admin' => "welcome#admin"
  get '/.well-known/acme-challenge/KsMFTs7WyL1Qp0fWMM6ngIPQw0P796gDPmUHecmBYqY' => "welcome#letsencrypt1"
  get '/.well-known/acme-challenge/UKlc744p08tlNn1lquxybh3fruOSue9T5qEN1eVY3Qo' => "welcome#letsencrypt2"
  get '/.well-known/acme-challenge/ZK5b5WgrDWKe_aKth25wXy1k_ebCR0PAqmYB0ARZ2H0' => "welcome#letsencrypt3"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[rules help letsencrypt1 letsencrypt2 letsencrypt3]
  
  def index
    @user_name = current_user.name;
    @users = User.all;
    @games = Game.all;
  end
  
  def show
  end
  
  def rules
  end
  
  def help
  end
  
  # For administrator only
  # GET /admin
  def admin
    @users = User.all;
    @user_name = current_user.name
    @user_id = current_user.id
    @recs = Game.all.order(created_at: :desc)
    @pagy, @records = pagy( @recs.order(created_at: :desc) )
  end
  
  def letsencrypt1
    render plain: "KsMFTs7WyL1Qp0fWMM6ngIPQw0P796gDPmUHecmBYqY.Q0_MeqZMHofUrqQw5JM1lIwytsur7x2iEgCzcPGJQ50"
  end
    
  def letsencrypt2
    render plain: "UKlc744p08tlNn1lquxybh3fruOSue9T5qEN1eVY3Qo.Q0_MeqZMHofUrqQw5JM1lIwytsur7x2iEgCzcPGJQ50"
  end
  
  def letsencrypt3
    render plain: "ZK5b5WgrDWKe_aKth25wXy1k_ebCR0PAqmYB0ARZ2H0.Q0_MeqZMHofUrqQw5JM1lIwytsur7x2iEgCzcPGJQ50"
  end
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/admin.html.erb
<body class="container splash">

	<% if current_user.id == 1 %>
	
		<div class="row">
			<%= image_tag "marbles_logo.png", alt: "Marbles Game Logo", class: "marbles_logo"%>
		</div>

		<div class="row">
			<h1 id="header" class="col-sm-6">Games Admin</h1>
		</div>

		<div class="row"></div>

		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th class="col-sm-1">Name</th>
		      <th class="col-sm-1">Date</th>
		      <th class="col-sm-1">Status</th>
			  <th class="col-sm-1">Updated</th>
		      <th class="col-sm-3">Teams/Players</th>
			  <th class="col-sm-1">Winner</th>
		      <th class="col-sm-1">Turn</th>
			  <th class="col-sm-1">Moves</th>
			  <th class="col-sm-2"></th>
		    </tr>
		  </thead>

	
		  <tbody>
			<% current_time = Time.now.to_i%>
		    <% @records.each do |game| %>
			  <% players = [game.yplayer, game.gplayer, game.rplayer, game.bplayer]%>
			  <% duration = game.updated_at.to_time.to_i - game.created_at.to_time.to_i %>
		      <tr>
				<% if (current_time - game.updated_at.to_time.to_i) <= 300 %>
		       	 	<td class="col-sm-2 blinking"><%= link_to game.name, game_path(game) %></td>
				<% else %>
					<td class="col-sm-2"><%= link_to game.name, game_path(game) %></td>
				<% end %>
		        <td class="col-sm-1"><%= game.start_date %></td>
		        <td class="col-sm-1"><%= game.status %></td>
				<td class="col-sm-1"><%= game.updated_at.strftime("%Y-%m-%d %H:%M")%></td>
		        <td class="col-sm-3">
					<% if game.ryteam!="" %>
						<div style="display:inline-block"><%= game.ryteam %></div>
						<div style="display:inline-block; color:red"><%= "(" + game.rplayer.split(" ")[0] + ", "%></div>
						<div style="display:inline-block; color:yellow"><%= game.yplayer.split(" ")[0] + ")"%></div>
					<% else %>
						<% if game.rplayer!="" %>
							<div style="display:inline-block; color:red"><%= game.rplayer.split(" ")[0] %></div>
						<% end %>
						<% if game.yplayer!=""%>
							<div style="display:inline-block; color:yellow"><%= " " + game.yplayer.split(" ")[0]%></div>
						<% end %>
					<% end %>		
					<% if game.gbteam!="" %>
						<br>
						<div style="display:inline-block"><%= game.gbteam %></div>
						<div style="display:inline-block; color:green"><%= "(" + game.gplayer.split(" ")[0] + ", " %></div>
						<div style="display:inline-block; color:blue"><%= game.bplayer.split(" ")[0] + ")"%></div>
					<% else %>
						<% if game.gplayer!="" %>
							<div style="display:inline-block; color:green"><%= game.gplayer.split(" ")[0] %></div>
						<% end %>
						<% if game.bplayer!="" %>
							<div style="display:inline-block; color:blue"><%= " " + game.bplayer.split(" ")[0] %></div>
						<% end %>
					<% end %>
				</td>			
				<td class="col-sm-1"><%= game.winner %></td>
				<% players = players.reject { |c| c.empty?} %>
				<% turn = players[(game.turn).to_i] %>
		        <td class="col-sm-1"><%= turn.split(" ")[0] %></td>
				<% if game.plays != 0%>
					<td class="col-sm-1"><div><%= game.plays %></div> <div><%=(duration/60.0).to_i%> min</div><div><%= (duration/game.plays).to_i %> s/m</div></td>
				<% else %>
					<td></td>
				<% end %>
				<div class="col-sm-2">		
					<td class="navbar-link">
						<%= link_to 'Play', game_path(game) %><span>&nbsp&nbsp</span>	
						<%= link_to 'Copy', copy_game_path(game.id),  data: {confirm: 'Are you sure you want to make a copy of this game?' } %><span>&nbsp&nbsp</span>
						<%= link_to 'Debug', debug_game_path(game) %>
						<%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
					</td>
				</div>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

		<h3 class="col-sm-12"><%== pagy_nav(@pagy) %></h3>
		
		
		<div class="row">
			<h1 id="header" class="col-sm-6">Users Admin</h1>
		</div>

		<div class="row"></div>

		<table class="table table-bordered">
		  <thead>
		    <tr>
		      <th class="col-sm-1">ID</th>
		      <th class="col-sm-2">Name</th>
		      <th class="col-sm-2">Email</th>
		      <th class="col-sm-1">Theme</th>
			  <th class="col-sm-2">Confirmed At</th>
		    </tr>
		  </thead>
		  <tbody>
			  <% @users.each do |u| %>
			  	<tr>
			  	  <td class="col-sm-1"><%= u.id %></td>
				  <td class="col-sm-2"><%= u.name %></td>
				  <td class="col-sm-2"><%= u.email %></td>
				  <td class="col-sm-2"><%= u.theme %></td>
				  <td class="col-sm-2"><%= u.confirmed_at.strftime("%Y-%m-%d %H:%M") %></td>
				</tr>
			  <% end %>
		  </tbody>
		</table>				
		
	<% else %>
		<%= "This view is for the administrator only "%>		
	<% end %>

</body>

app/views/welcome/help.html.erb
<body class="splash">
	<div class="container form_style">

	<h1 id="header">The Game</h1>
	<p>This site is for playing the game of Marbles which has been very popular with our family and friends for the past several years.  It was developed in 2020 after the Covid-19 pandemic restrictions limited our ability to play together around the table.  Please also read the Rules page before playing for the first time.  Have fun and send any comments, questions or suggestions to <%= mail_to "wmshockey@gmail.com" %>.  Thank-you!! </p>

	<h1>How to Play</h1>

	<p>The online computer version plays with the same rules as the original board game.  See the <%= link_to "Rules", '/welcome/rules', :style => "color:red" %> page on this site for details.  There are few points to note when playing online:</p>

	<ul class="bullets">

	<%= image_tag "marble_game_screenshot2.png", alt: "Marbles Game Screenshot", :class => "marbles_board" %>

		<li>The minimum requirements to run the online game is a desktop or laptop computer with either a Windows 10, ChromeOS or Mac OSX operating system with at least a 13 inch screen size and a web browser that supports HTML5.  This can be any recent version (since 2014) of Chrome, Firefox, Internet Explorer (version 9 or later), Edge or Safari.  The game can be played with standard HD laptop resolutions of 1366x768 or better and depending on the screen size, you may have set the zoom level on your browser to get the whole game board to fit on the screen. The game can be played with an iPad or other touch screen devices but is not ideally suited for it.</li>
	
		<li>In order to play the game on the marblemind.ca website, you will need a user account.  Use the Sign-up link on the Welcome page to register a user account.  The game is free to play.</li>
	
		<li>To initially create a game, you click on the "New Game" button when viewing the list of games.  The "New Game" form will let you enter whatever name you wish to give to the game, and let you assign which users will be playing which colors in the game.  You can also play as teams.  If you enter a team name below the Yellow and Red players, they will form one team.  Similarly if you enter a team name below the Green and Blue players, they will form the other team.</li>
	
		<li>When creating a game, notice that there is an option to turn the "Auto refresh" off.  However you should always leave this set to the default setting "on" unless you are on a very slow dial-up type network.  When the Auto refresh is turned off, each player will have to hit the yellow "Refresh" button whenever a player announces that they have finished their turn.</li>

		<li>Playing a card and moving a marble on the board is done using the standard drag and drop operation performed with a mouse or trackpad on your computer</li>
	
		<li>The computer handles all the card shuffling and card dealing.</li>
	
		<li>If it is your turn to play, a green "Start Turn" button will appear at the bottom of the board on the left hand side.  You must click on this start button first before you can play a card or move a marble.  When you have finished your turn, you click on the red button "End Turn".  If your move was valid, the play will be turned over to the next player and you will see a "waiting for..." message appear on the bottom of the board.</li>

	<li>Other players cannot see your cards on the screen.</li>

	<li>The green arrow that points to marbles on the screen is showing you which marbles moved in the previous turn. </li>

	<%= image_tag "new_game_screenshot.png", alt: "New Game Screenshot", :class => "marbles_board" %>

		<li>When "killing" another marble you put your marble on top of the marble to be "killed" and the computer will automatically place the killed marble back into it's starting row.  You cannot manually move a marble into it's starting row.  So if killing multiple marbles with a 7 card, you have to land on each marble to be killed to send them back to their starting row.</li>
	
		<li>When playing a Jack, you place your marble on top of the marble you want to swap with and the computer will automatically move the displaced marble to the proper spot.</li>
	
		<li>The computer will check all moves to make sure they are valid moves.  If not, the board will be reset to the start of your move and you will be asked to take your turn over again.</li>
	
		<li>The triangle symbol &#x25c4; shown beside a player's name means that this player is the one who plays first following the next card deal.  The player who plays first after a deal will change to the next player whenever a full deck is dealt. </li>

		<li>If you can't make a play, just press the red "End Turn" button without playing a card or moving a marble.  You will be asked to confirm that you are unable to play.  In this case a "Can't Play" label will appear next to your name on the board and the other players will proceed to take their turns until the hand is fully played.</li>
	
		<li>Just as with the board game, you should play your card first and then move your marble.</li>
	
		<li>Your card hand will initially appear in the centre of the board, just below the centre hole.  If you have enough screen space and want to move it elsewhere to the side of the board you can do so.  It must be your turn in order to do it though.  Behind the card hand is an image of a hand.  You can select that wrist of the hand to drag and drop the entire hand to another place on the side. </li>
	
		<li>The white numbers shown below each players names on the board, are the number of cards left in their hand.  Similarly, the numbers shown below the discard pile and deck are the number cards left in those piles.  The total of all those numbers will always equal 56, the total number of cards in the deck.</li>
		
		<li style="color:red">NEW: There is a special mercy feature in the game to allow a player to put another player's discards back into their hand if they accidentally discarded them thinking they could not make a play.  In this case, the player whose turn is next to play will start their turn and instead of playing their own cards and marbles, they will drag and drop the discarded cards next to the discard area over to the name of the player who needs their cards back.  The drop must be precise, with the cursor placed directly on top of the players name in order for it to work.  When the cards have been dropped on the name, the player's turn will end.  The game will then proceed with the player who accidentally threw their cards in getting to take their turn over.</li>
	
		<li>Note that if only two players are playing, they should put their names into either the Yellow or Red colors so that they play opposite each other on the board.  Also note that it is possible for one user to play more than one color but this is a different variation of the game.</li>
	
		<li>The game is more fun and interactive if you have an audio channel open so all players can talk to each other while playing.  This can be done by putting your phone on speaker when connected with facetime audio, zoom audio, skype or just a standard phone call.</li>
	
		<li>Other than the above, the rules of the computer game are the same as the actual board game and are listed on the Rules page of this site.</li>
	</ul>

	</div>
</body>

app/views/welcome/index.html.erb
<body class="container splash">

	<div class="row">
		<%= image_tag "marbles_logo.png", alt: "Marbles Game Logo", class: "marbles_logo"%>
	</div>
	
	<div class= "row">
		<h2 id="header" style="color:blue">Welcome to the Online Game of Marbles</h2>
	</div>

		<h4 class="col-sm-4"><strong><%= link_to 'Show All My Games', '/games'%></strong></h4>
		<div class="col-sm-8 text-info bg-info">Update 2021-03-18: Show scores only for matches the player is a participant in.</div>

	<br><br>

	<% ryteams = @games.map {|g| g.ryteam}.uniq %>
	<% gbteams = @games.map {|g| g.gbteam}.uniq %>
	<% teams = ryteams.concat(gbteams).uniq.sort! %>
	<% current_time = Time.now.to_i%>
	<% current_games = Game.all.where("updated_at > ?", 2.minutes.ago) %>

	<div style="font-style: italic"><%= "Games currently in progress:  #{current_games.count}"%></div>
	
	<% mygames = @games.select {|g| [g.rplayer, g.yplayer, g.bplayer, g.gplayer].include?(@user_name)} %>
	<% team_matchups = [] %>
	<% i = 0 %>
	<% mygames.each do |m| %>
		<% if m.ryteam != "" && m.gbteam != "" %>
			<% team_matchups.push([m.ryteam, m.gbteam, 0, 0])%>
			<% i = i + 1 %>
		<% end %>
	<% end %>
	<% team_matchups = team_matchups.uniq.sort! %>
	<% i = 0 %>
	<% while i < team_matchups.length do %>
		<% match_games = mygames.select {|g| g.ryteam==team_matchups[i][0] && g.gbteam==team_matchups[i][1]} %>
		<% ry_gamewins = match_games.select {|g| g.winner == team_matchups[i][0]} %>
		<% gb_gamewins = match_games.select {|g| g.winner == team_matchups[i][1]} %>
		<% team_matchups[i][2] = ry_gamewins.count() %>
		<% team_matchups[i][3] = gb_gamewins.count() %>
		<% i = i + 1 %>		
	<% end %>

	<% team_stats = []%>
	<% i = 0%>
	<% teams.each do |t| %> 
		<% @team_games = (@games.select {|g| ( (g.ryteam == t || g.gbteam == t) && g.status=="Finished") } ) %>
		<% if !@team_games.empty?%>
			<% if @team_games[0].ryteam == t %>
				<% player1 = @team_games[0].rplayer%>
				<% player2 = @team_games[0].yplayer%>
			<% else%>
				<% player1 = @team_games[0].gplayer%>
				<% player2 = @team_games[0].bplayer%>
			<% end %>
			<% num_games = @team_games.count()%>
			<% num_wins = (@team_games.select {|g| g.winner == t}).count()%>
			<% num_losses = num_games - num_wins %>
			<% team_stats[i] = [t, player1, player2, num_games, num_wins, num_losses]%>
			<% i = i + 1%>
		<% end %>
	<% end %>
	<% team_stats.sort_by! { |a| -a[0] }%>
	

	<h4>Score Board</h4>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Teams</th>
				<th>Games Played</th>
				<th>Score</th>
			</tr>
		</thead>
		
		<tbody>
			<% i = 0 %>
			<% while i < team_matchups.length do %>
				<tr>
					<% ryteam = team_matchups[i][0] %>
					<% gbteam = team_matchups[i][1] %>
					<% rywins = team_matchups[i][2] %>
					<% gbwins = team_matchups[i][3] %>
					<% num_games = rywins + gbwins %>
					<td><%= ryteam %> vs <%= gbteam %></td>
					<td><%= num_games %></td>
					<td><%= ryteam%>: <%= rywins %> | <%= gbteam %>: <%= gbwins%></td>
				</tr>
				<% i = i + 1 %>
			<% end %>
		</tbody>
	</table>


	<h4>Teams</h4>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Team</th>
				<th>Players</th>
				<th>Games Played</td>
			</tr>
		</thead>
	
		<tbody>
			<% team_stats.each do |t| %>
				<% if t[0] != "" %>
					<tr>
						<td><%= t[0]%></td>
						<td><%= t[1]%>, <%= t[2]%></td>
						<td><%= t[3]%></td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
	</table>


	<% player_stats = []%>
	<% winning_players = []%>
	<% i = 0%>
	<% @users.each do |u| %> 
		<% player = u.name %>
		<% @player_games = (@games.select {|g| ([g.rplayer, g.yplayer, g.gplayer, g.bplayer].include?(player)) && g.status=="Finished"}) %>
		<% num_games = @player_games.count()%>
		<% wins = 0%>
		<% losses = 0%>
		<% if !@player_games.empty?%>
			<% @player_games.each do |g| %>
				<% if g.winner == g.ryteam %>
					<% winning_players[0] = g.rplayer%>
					<% winning_players[1] = g.yplayer%>
				<% elsif g.winner == g.gbteam%>
					<% winning_players[0] = g.gplayer%>
					<% winning_players[1] = g.bplayer%>
				<% else%>
					<% if (g.yplayer.split(" ")[0] == g.winner) %>
						<% winning_players[0] = g.yplayer %>
					<% elsif (g.rplayer.split(" ")[0] == g.winner) %>
						<% winning_players[0] = g.rplayer%>
					<% elsif (g.gplayer.split(" ")[0] == g.winner)%>
						<% winning_players[0] = g.gplayer%>
					<% elsif (g.bplayer.split(" ")[0] == g.winner)%>
						<% winning_players[0] = g.bplayer%>
					<% end %>
					<% winning_players[1] = "" %>
				<% end %>
				<% if (winning_players.include?(player)) %>
					<% wins = wins + 1%>
				<% else%>
					<% losses = losses + 1%>
				<% end %>
			<% end %>
			<% winPct = ((wins.to_f/num_games.to_f)*100.0).to_i %>
			<% player_stats[i] = [player, num_games, wins, losses, winPct]%>
			<% i = i + 1%>
		<% end %>
	<% end %>

	<% player_stats.sort_by! { |a| a[0]}%>
	
	<br>
	<h4>Players</h4>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Player</th>
				<th>Games Played</th>
				<th>Wins</th>
				<th>Losses</th>
				<th>Win %</th>
			</tr>
		</thead>
		
		<tbody>
			<% player_stats.each do |u| %>
				<tr>
					<td><%= u[0]%></td>
					<td><%= u[1]%></td>
					<td><%= u[2]%></td>
					<td><%= u[3]%></td>
					<td><%= u[4]%></td>
				</tr>
			<% end %>
			<td><%= "Total"%></td>
			<td><%= @games.count %></td>
		</tbody>
	</table>
	  
	  <div class="row col-sm-12">Developed by Warren Shockey in 2020.  Special thanks to beta testers Randy and Lois Schneider, Lenora, Adam, Trina, Merle and Flora Shockey.  The software is copyright of Phastware Consulting Ltd. and is licensed under GNU GPL v3.  Please send any feedback, comments or questions to <%= mail_to "wmshockey@gmail.com"%>.</div>
	  <div class="row col-sm-12"></div>

  
</body>

app/views/welcome/rules.html.erb
<body class="splash">
	
	<div class="container form_style">

	<h1 id="header">The Original Board Game Rules</h1>
	<h2>Object of the game:</h2>
	

	<p>To get all four of your marbles and your partners marbles to the home spots. First team to do that wins.</p>

	<ul class="bullets">

	<li>Played with a regular deck of 52 cards plus 4 jokers. </li>

	<li>Throw the dice to determine who deals first. </li>

	<li>Players take turns dealing all 56 cards - 5 to each player and after those are played, another 5 to each player, and after those are played 4 more to each player completing the deal. Then the player to your left deals. </li>

	<li>In order to start a marble on the board you need one of the following cards: <br>
	- Joker (or use it to move 15 spaces forward) <br>
	- King (or use it to move 13 spaces forward) <br>
	- Ace (or move 1 space forward)<br></li>

	<li>You cannot jump a marble. If you land directly on it, you knock it back to start position where the player must have a Joker, King or Ace to move it out and start again. </li>

	<li>Once a card is placed on the table it must be played. Unless it is not a playable card. </li>

	<li>You must play each playable card. If you cannot play, throw all of your cards face up on the table and sit out of play until the next set of cards are dealt. </li>

	<li>4 card: moves 4 spaces BACKWARDS only. All other cards move forward. </li>

	<li>JACK : switch places - one of your playable marbles with another marble (partner or opponent). Once marbles are in a home spot they cannot be switched, moved backwards or knocked off. </li>

	<li>7 card: the only card you can separate into different moves/marbles if you choose. Eg. Move 2 spaces, knock a marble off then continue on with as many moves as the 7 spots allow, or move part with one marble, part with another, etc. You MUST move 7 spaces in total. You cannot use only part of the 7. </li>

	<li>All other cards move forward at face value. Queen moves 12 spots forward. </li>

	<li>Center spot: you can move into this spot from any 6 hole (painted black) instead of moving one more spot on the outside. You can also use a 4 card to back into the center spot. Your marble must remain in the center for one turn (you cannot carry on and exit with a 7 card). You can exit via any black 6 spot on the board. </li>

	<li>You cannot use a 4 to go backwards into the home spaces. You do not pass your entrance to the home spots. </li>

	<li>Once all of your marbles have entered play, you can use your cards to move your partner's marbles as if they were your own. If one of your marbles gets knocked off, cannot continue to play your partner's marbles until you again have all of your marbles in play. </li>

	</ul>

	</div>
</body>