config/routes.rb
Rails.application.routes.draw do
  resources :games do 
    member do 
      get 'play'
      get 'debug'
      get 'query'
      get 'query2'
      get 'copy'
    end
  end
  
  devise_for :users
  get 'welcome/index'
  get 'welcome/rules' => "welcome#rules"
  get 'welcome/help' => "welcome#help"
  get 'welcome/admin' => "welcome#admin"
  get '/.well-known/acme-challenge/KsMFTs7WyL1Qp0fWMM6ngIPQw0P796gDPmUHecmBYqY' => "welcome#letsencrypt1"
  get '/.well-known/acme-challenge/UKlc744p08tlNn1lquxybh3fruOSue9T5qEN1eVY3Qo' => "welcome#letsencrypt2"
  get '/.well-known/acme-challenge/ZK5b5WgrDWKe_aKth25wXy1k_ebCR0PAqmYB0ARZ2H0' => "welcome#letsencrypt3"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  
end

app/models/game.rb
class GameValidator < ActiveModel::Validator
  def validate(record)
    if record.name==""
      record.errors[:base] << 'A Game Name is required.'
    end
  	if record.ryteam!="" && (record.rplayer=="" || record.yplayer=="")
  		record.errors[:base] << 'Need two players to form a team, otherwise leave the team field blank.'
    end
  	if record.gbteam!="" && (record.gplayer=="" || record.bplayer=="")
  		record.errors[:base] << 'Need two players to form a team, otherwise leave the team field blank.'
  	end  
    if (record.yplayer=="" && record.rplayer=="" && record.gplayer=="" && record.bplayer=="")
      record.errors[:base] << 'Need to have at least one player to create a game.'    
    end
    @games = Game.all
    team_name_conflict = ""
    @games.each do |n|
      if (n.ryteam==record.ryteam)
        pnames = [n.rplayer, n.yplayer]
        if (!pnames.include?(record.rplayer) || !pnames.include?(record.yplayer) )
          team_name_conflict = record.ryteam
        end
      end
      if(n.gbteam==record.ryteam)
        pnames = [n.gplayer, n.bplayer]
        if (!pnames.include?(record.rplayer) || !pnames.include?(record.yplayer) )
          team_name_conflict = record.ryteam
        end
      end
    end
    if team_name_conflict != ""
      record.errors.add(:base, 'Team name ' + team_name_conflict + " is already taken.  Please choose a different team name.")
    end
    team_name_conflict = ""
    @games.each do |n|  
      if (n.ryteam==record.gbteam)
        pnames = [n.rplayer, n.yplayer]
        if (!pnames.include?(record.gplayer) || !pnames.include?(record.bplayer) )
          team_name_conflict = record.gbteam
        end 
      end
      if (n.gbteam==record.gbteam)
        pnames = [n.gplayer, n.bplayer]
        if (!pnames.include?(record.gplayer) || !pnames.include?(record.bplayer) )
          team_name_conflict = record.gbteam
        end
      end
    end
    if team_name_conflict != ""
      record.errors.add(:base, 'Team name ' + team_name_conflict + " is already taken.  Please choose a different team name.")
    end
  end
end

class Game < ApplicationRecord
  include ActiveModel::Validations
  validates :name, :presence => true
  validates_uniqueness_of :name, :message => ' - %{value} game name has already been taken'
  validates_with GameValidator

  def copy(game)
    game_copy = game.dup
    new_name = game.name + "-copy"
    game_copy.name = new_name
    game_copy.save
    return game_copy
  end  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :debug, :play, :query, :query2, :destroy, :copy]
  before_action :get_teams, only: [:new, :create, :edit, :update, :debug, :play]
  
  # GET /games
  # GET /games.json
  def index
    @user_name = current_user.name
    @user_id = current_user.id
    @recs = Game.all.where("yplayer='#{@user_name}' or rplayer='#{@user_name}' or gplayer='#{@user_name}' or bplayer='#{@user_name}'").order(created_at: :desc)
    @pagy, @records = pagy( @recs.order(created_at: :desc) )
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/1/query
  # GET /games/1.json
  def query
    render json: @game
  end

  # GET /games/1/query2
  # GET /games/1.json  
  def query2
    render json: @game
  end

  # GET /games/new
  def new
    @game = Game.new
    @users = User.all
    @user_name = current_user.name
    @user_id = current_user.id
    @games = Game.all.where("yplayer='#{@user_name}' or rplayer='#{@user_name}' or gplayer='#{@user_name}' or bplayer='#{@user_name}'")
  end

  # GET /games/1/play
  def play
    @users = User.all
  end

  # GET /games/1/edit
  def edit
    @users = User.all
  end

  # Get /game/1/debug
  def debug
    @users = User.all
  end  

  # GET /games/1/copy
  def copy
    @game = Game.find(params[:id])
    respond_to do |format|
      game_copy = @game.copy(@game)
      if game_copy
        format.html { redirect_to welcome_admin_url, notice: "Game #{@game.name} was successfully copied to: #{game_copy.name}." }
        format.json { head :no_content }
      else
        flash[:error] = "Game copy failed."
        format.html { render :show, notice: 'Game copy failed.' }
        format.json { render json: game_copy.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /games
  # POST /games.json
  def create
    @users = User.all
    @game = Game.new(game_params)
    @game.start_date = DateTime.now.strftime('%Y-%m-%dT%H:%M')
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: '** Game was successfully created. **' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        if params[:commit]=="End Turn"
          format.html { redirect_to @game }
        else
          format.html { redirect_to games_url, notice: '** Game was successfully updated. **'}
        end
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy    
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url, notice: '** Game was successfully destroyed. **' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @users = User.all
      @game = Game.find(params[:id])
      @user_name = current_user.name
      @user_email = current_user.email
      turn = @game.turn.to_i
      get_plist
      if (@plist.include?(@user_name) || @user_email == "wmshockey@gmail.com")
        @player = @plist[turn]
      else
        respond_to do |format|
          format.html { redirect_to games_url, alert: '** You are not a player in this game. **' }
          format.json { head :no_content }
        end
      end
    end

    def get_teams
      @games = Game.all
    	ryteams = @games.map {|g| g.ryteam+": ("+g.yplayer+","+g.rplayer+")"}.uniq
    	gbteams = @games.map {|g| g.gbteam+": ("+g.gplayer+","+g.bplayer+")"}.uniq
    	@teams = ryteams.concat(gbteams).uniq.sort!
      @teams = @teams.select {|t| t[0]!=":"}
    end
 
    def get_plist 
      @plist = []
      if (@game.yplayer!="")
        @plist.push(@game.yplayer)
      end
      if (@game.gplayer!="") 
        @plist.push(@game.gplayer)
      end
      if (@game.rplayer!="")
        @plist.push(@game.rplayer)
      end
      if (@game.bplayer!="")
        @plist.push(@game.bplayer)
      end
    end
    
    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :id, :start_date, :status, :yplayer, :gplayer, :rplayer, :bplayer, :ryteam, :gbteam, :turn, :comment, :board, :deck, :discardpile, :greenhand, :redhand, :bluehand, :yellowhand, :screen, :winner, :refresh, :moved, :plays, :updated_at, :firstturn, :message)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_calcfields.html.erb
	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Game ID"%> </div>
		<div class="col-sm-10 top"><%= form.number_field :id %></div>
	</div>

	<div class="row">
		<div class="col-sm-2"><%= form.label "Status:" %></div>
		<div class="col-sm-10"><%= form.text_field :status %></div>
	</div>
	
	<div class="row">
		<div class="col-sm-2"><%= form.label "Turn:" %></div>
		<div class="col-sm-2"><%= form.text_field :turn, :size=>"5" %></div>
		<div class="col-sm-8 top"><%= @plist%></div>
	</div>
		  	
	<div class="row">
		<div class="col-sm-2"><%= form.label "First Turn:" %></div>
		<div class="col-sm-10"><%= form.text_field :firstturn, :size=>"5" %></div>	  		  
	</div>

	<div class="row">
		<span class="col-sm-2 top"><%= form.label "Hand"%></span>
		<span class="col-sm-2 top"><%= form.text_area :yellowhand %></span>
		<span class="col-sm-2 top"><%= form.text_area :redhand %></span>
		<span class="col-sm-2 top"><%= form.text_area :greenhand %></span>
		<span class="col-sm-2 top"><%= form.text_area :bluehand %></span>
	    <span class="col-sm-2"></span>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Deck"%></div>
		<div class="col-sm-8 top"><%= form.text_area :deck, cols: "110", rows: "2"%></div>
	    <span class="col-sm-2"></span>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Board"%></div>
		<div class="col-sm-8 top"><%= form.text_area :board, cols: "110", rows: "2"%></div>
	    <span class="col-sm-2"></span>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Discard Pile"%></div>
		<div class="col-sm-8 top"><%= form.text_area :discardpile, cols: "110", rows: "2"%></div>
	    <span class="col-sm-2"></span>
	</div>


	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Comment"%></div>
		<div class="col-sm-8 top"><%= form.text_area :comment, cols: "110", rows: "2"%></div>
		<span class="col-sm-2"></span>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Message"%></div>
		<div class="col-sm-8 top"><%= form.text_area :message, cols: "110", rows: "2"%></div>
		<span class="col-sm-2"></span>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Screen Coordinates"%> </div>
		<div class="col-sm-10 top"><%= form.text_field :screen, :size=>"50"%></div>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Moved Marbles"%> </div>
		<div class="col-sm-10 top"><%= form.text_field :moved, :size=>"50"%></div>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Winner"%> </div>
		<div class="col-sm-10 top"><%= form.text_field :winner, :size=>"50"%></div>
	</div>

	<div class="row">
		<div class="col-sm-2 top"><%= form.label "Plays Made"%> </div>
		<div class="col-sm-10 top"><%= form.number_field :plays%></div>
	</div>

	<br>

app/views/games/debug.html.erb
<h1 id="header">Debug Game</h1>
<div class="col-sm-12 hidden" id="form_name"><%= "game" %></div>
<br>
<%= form_with(model: @game, local: true) do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<body class="container">
	
	<br>
	<%= render partial: "editfields", locals: {form: form} %>
	<br>

	<div class=" container form_style">
		<%= render partial: "calcfields", locals: {form: form} %>
	</div>
	<br>
		
    <div class="row" >
      <div class="col-sm-2"><%= form.submit "Save", class:"btn btn-danger", id:"debugSave"%></div>
      <div class="col-sm-10"><%= link_to 'Back', games_path%></div>
    </div>

	<br>

	<div class="row container form_style">
	<% i = 0%>
	<% board_array = @game.board.split(",")%>
	<% until i > 96  do%>
		<div class="col-sm-1"><%= i%>:<%= board_array[i]%></div>
		<% i = i + 1%>
	<% end %>
	</div>

	<br>
 	<div class="row"><%= image_tag "marbles_board_numbered.png", alt: "Marbles Clip Art"%></div>

</body>
<% end %>

	

app/views/games/edit.html.erb
<h2 id="header">Edit Game</h2>
<div class="col-sm-12 hidden" id="form_name"><%= "game" %></div>
<br>
<%= form_with(model: @game, local: true) do |form| %>


<body class="container splash">
	
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	
	<%= render partial: "editfields", locals: {form: form} %>

	<div class="hidden">
		<%= render partial: "calcfields", locals: {form: form} %>
	</div>
	
	<br><br>
	
    <div class="row" >
      <div class="col-sm-2"><%= form.submit "Save", class:"btn btn-danger btn-lg", id:"Save"%></div>
      <h3 class="col-sm-10"><%= link_to 'Back', games_path%></h3>
    </div>

</body>
<% end %>

app/views/games/index.html.erb
<body class="container splash">

<div class="row">
	<%= image_tag "marbles_logo.png", alt: "Marbles Game Logo", class: "marbles_logo"%>
</div>

<div class="row">
	<h1 id="header" class="col-sm-6">Games</h1>
	<div class="col-sm-6 text-right"><%= button_to "New Game", new_game_path, method: :get, :class => 'btn-success btn-lg' %></div>
</div>

<div class="row">	
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-sm-2">Name</th>
      <th class="col-sm-1">Date</th>
      <th class="col-sm-1">Status</th>
      <th class="col-sm-3">Teams/Players</th>
	  <th class="col-sm-1">Winner</th>
      <th class="col-sm-1">Turn</th>
	  <th class="col-sm-1">Moves</th>
	  <th class="col-sm-2"></th>
    </tr>
  </thead>

	
  <tbody>
	<% current_time = Time.now.to_i%>
    <% @records.each do |game| %>
	  <% players = [game.yplayer, game.gplayer, game.rplayer, game.bplayer]%>
      <tr>
		<% if (current_time - game.updated_at.to_time.to_i) <= 300 %>
       	 	<td class="col-sm-2 blinking"><%= link_to game.name, game_path(game) %></td>
		<% else %>
			<td class="col-sm-2"><%= link_to game.name, game_path(game) %></td>
		<% end %>
        <td class="col-sm-1"><%= game.start_date  %></td>
        <td class="col-sm-1"><%= game.status %></td>
        <td class="col-sm-2">
			<% if game.ryteam!="" %>
				<div style="display:inline-block"><%= game.ryteam %></div>
				<div style="display:inline-block; color:red"><%= "(" + game.rplayer.split(" ")[0] + ", "%></div>
				<div style="display:inline-block; color:yellow"><%= game.yplayer.split(" ")[0] + ")"%></div>
			<% else %>
				<% if game.rplayer!="" %>
					<div style="display:inline-block; color:red"><%= game.rplayer.split(" ")[0] %></div>
				<% end %>
				<% if game.yplayer!=""%>
					<div style="display:inline-block; color:yellow"><%= " " + game.yplayer.split(" ")[0]%></div>
				<% end %>
			<% end %>		
			<% if game.gbteam!="" %>
				<br>
				<div style="display:inline-block"><%= game.gbteam %></div>
				<div style="display:inline-block; color:green"><%= "(" + game.gplayer.split(" ")[0] + ", " %></div>
				<div style="display:inline-block; color:blue"><%= game.bplayer.split(" ")[0] + ")"%></div>
			<% else %>
				<% if game.gplayer!="" %>
					<div style="display:inline-block; color:green"><%= game.gplayer.split(" ")[0] %></div>
				<% end %>
				<% if game.bplayer!="" %>
					<div style="display:inline-block; color:blue"><%= " " + game.bplayer.split(" ")[0] %></div>
				<% end %>
			<% end %>
		</td>			
		<td class="col-sm-1"><%= game.winner %></td>
		<% players = players.reject { |c| c.empty?} %>
		<% turn = players[(game.turn).to_i] %>
        <td class="col-sm-1"><%= turn.split(" ")[0] %></td>
		<td class="col-sm-1"><%= game.plays %></td>
		<div class="col-sm-2">		
			<td class="navbar-link">
				<%= link_to 'Play', game_path(game) %><span>&nbsp&nbsp</span>	
				<%= link_to 'Edit', edit_game_path(game) %><span>&nbsp&nbsp</span>
		        <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</div>
      </tr>
    <% end %>
  </tbody>
</table>

<h3 class="col-sm-12"><%== pagy_nav(@pagy) %></h3>

</body>

app/views/games/new.html.erb
<h2 id="header">New Game</h2>

<div id="form_name", class="hidden"><%= "game" %></div>

<%= form_with(model: @game, local: true) do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<body class="container">
		<br>
		<%= render partial: "editfields", locals: {form: form} %>
		<br>

		<div class="hidden">
			<%= render partial: "calcfields", locals: {form: form} %>
		</div>
				
		<div class="row">
		  <div class="col-sm-2" >
		    <%= form.submit "Save", class:"btn-lg btn-primary", id:"Save"%>
		  </div>
		  <h3 class="col-sm-1"><%= link_to 'Back', games_path%></h3>
		</div>

	</body>

<% end %>

app/views/games/play.html.erb
<div class="line2">
	<span class="boardlabel" id="header">Marbles Game</span>
	<strong><span class="boardlabel">: <%= @game.name %></span></strong><div style="color:white">Moves: <%= @game.plays %></div>
</div>

<% if @user_name == @player %>

		<div id="form_name", class="hidden"><%= "game" %></div>

		<%= form_with(model: @game, local: true) do |form| %>

			<div id="btnArea">
			    <%= form.submit "End Turn", class:"btn btn-danger btn-lg", id:"Save"%>
			</div>
			<div class="btnRestart"><%= link_to "Restart Turn", play_game_path(@game), id: "Restart", class:"btn btn-warning btn-sm"%></div>


			<% if @game.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
			      <ul>
			      <% @game.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			<% end %>

			<div id="myTable" width="1400" height="1080">
				<canvas id="myCanvas" width="1400" height="1080"></canvas>
			</div>

			<div class="hidden">	
				<br><br><br><br>
				<%= render partial: "editfields", locals: {form: form} %>
				<br>
			</div>

			<div class="hidden">
				<%= render partial: "calcfields", locals: {form: form} %>
			</div>

		<% end %>

<% else %>
	<span id="msgArea" class = "text-danger bg-danger">It's not your turn.</span>
	<span> <%= link_to 'Back', games_path%></span>
<% end %>


<script>
	$("#Restart").on("click", function(evt){
		if (!confirm("Marbles and cards will be reset to start of turn positions.")) {
	        evt.preventDefault();
	        return false;			
		}
	});	
</script>

	

app/views/games/query.html.erb
<body>

	<div>
		<div id="game_id"><%= @game.id %></div>
		<div id="game_name"><%= @game.name %></div>
		<div id="game_status"><%= @game.status %></div>
		<div id="game_refresh"><%= @game.refresh %></div>
		<div id="game_turn"><%= @game.turn %></div>
		<div id="game_plays"><%= @game.plays %></div>
	</div>

</body>

app/views/games/query2.html.erb
<body>

	<div>
		<div id="game_id"><%= @game.id %></div>
		<div id="game_name"><%= @game.name %></div>
		<div id="game_ryteam"><%= @game.ryteam %></div>
		<div id="game_gbteam"><%= @game.gbteam %></div>
		<div id="game_rplayer"><%= @game.rplayer %></div>
		<div id="game_yplayer"><%= @game.yplayer %></div>
		<div id="game_gplayer"><%= @game.gplayer %></div>
		<div id="game_bplayer"><%= @game.bplayer %></div>
	</div>

</body>

app/views/games/show.html.erb
<head>
	<meta charset="UTF-8"/>	
</head>

<% if @game.yplayer==@user_name || @game.rplayer==@user_name || @game.gplayer==@user_name || @game.bplayer==@user_name %>

	<span class="line2">
		<span class="boardlabel" id="header">Show Game</span>
		<strong><span class="boardlabel">: <%= @game.name %></span></strong><div style="color:white">Moves: <%= @game.plays %></div>
	</span>

	<% if @game.status == "Finished"%>
		<span class = "text-success bg-success msgArea">
			<%= "\u{1F44F} Congratulations to the "%><strong><%= @game.winner%></strong><%= " for winning the game!! \u{1F44F} \u{1F3C6}"%>
		</span>
	<% else %>
		<span id="btnArea">
			<% if @user_name == @player %>
				<% @button_text = " Start Turn" %>
				<%= button_to @button_text, play_game_path(@game), method: :get, class:'btn btn-success btn-lg blinking', id:"Start" %>
			<% else %>
				<span class = "text-warning bg-warning">
					<%= "** Waiting for " + @player.split(" ")[0] + " **"%>
				</span>
				<br>
				<div style="padding-top: 10px"><%= button_to "Refresh", game_path(@game), method: :get, class:'btn btn-warning btn-sm'%></div>
			<% end %>

		</span>
	<% end %>

	<body>

	<div id="myTable" width=1400 height=1080>
		<canvas id="myCanvas" width=1400 height=1080></canvas>
	</div>

	<div class="hidden">
		<div id="game_id"><%= @game.id %></div>
		<div id="game_name"><%= @game.name %></div>
		<div id="game_start_date"><%= @game.start_date %></div>
		<div id="game_status"><%= @game.status %></div>
		<div id="game_turn"><%= @game.turn %></div>
		<div id="game_firstturn"><%= @game.firstturn %></div>		

		<div id="game_yplayer"><%= @game.yplayer %></div>
		<div id="game_gplayer"><%= @game.gplayer %></div>
		<div id="game_rplayer"><%= @game.rplayer %></div>
		<div id="game_bplayer"><%= @game.bplayer %></div>
		<div id="game_ryteam"><%= @game.ryteam %></div>
		<div id="game_gbteam"><%= @game.gbteam %></div>		
		<div id="game_refresh"><%= @game.refresh %></div>
				
		<div id="game_yellowhand"><%= @game.yellowhand %></div>
		<div id="game_greenhand"><%= @game.greenhand %></div>
		<div id="game_redhand"><%= @game.redhand %></div>
		<div id="game_bluehand"><%= @game.bluehand %></div>
		<div id="game_deck"><%= @game.deck%></div>
		<div id="game_board"><%= @game.board %></div>
		<div id="game_discardpile"><%= @game.discardpile %></div>
		<div id="game_comment"><%= @game.comment %></div>
		<div id="game_message"><%= @game.message %></div>
		<div id="game_screen"><%= @game.screen %></div>
		<div id="game_moved"><%= @game.moved %></div>
		<div id="game_winner"><%= @game.winner%></div>
		<div id="game_plays"><%= @game.plays %></div>
	</div>			

	</body>

<% else %>

	<span class="text-warning bg-warning msgArea">You are not a player on this game.  Please press the Back button.</span>
	<div class="col-sm-12"><%= link_to 'Back', games_path%></div>
	
<% end %>